# Site
name: "Hunter ACM"
title: "Hunter ACM"
description: "Hunter ACM is a community of Hunter College students interested in CS and tech. We design, code, build, and learn about topics not taught in our classes."
meta_description: "Hunter ACM is a community of Hunter College students interested in CS and tech. We design, code, build, and learn about topics not taught in our classes."
logo: assets/images/logo.png
favicon: assets/images/favicon.png
paginate: 12
facebook: hunteracm
slack: hunteracm
github: hunteracm
medium: hunteracm

# Authors
authors:
  board:
    name: board
    display_name: "Hunter ACM Board"
    gravatar: fcb7a88ce4ed61c9470d8a3dec7b5211
    web: https://hunter.acm.org
    description: "The Hunter ACM board strives to make a safe, welcoming, and inclusive community for students who want to design, code, build, and learn about topics not taught in our classes."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: /category/:name/
    
# Other
markdown: kramdown
highlighter: rouge